import { Course } from '../../api/course/course.js';
import { _ } from 'meteor/underscore';

/**
 * A list of Stuff to pre-fill the Collection.
 * @type {*[]}
 */
const courseSeeds = [
  { name: 'ICS111',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS141',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS211',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS212',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS215',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS241',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS290',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS311',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS312',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS313',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS314',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS321',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS331',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS332',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS351',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS355',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS361',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS390',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS414',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS415',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS419',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS421',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS422',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS423',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS424',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS425',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS426',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS431',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS432',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS435',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS441',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS442',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS443',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS451',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS452',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS1455',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS461',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS464',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS465',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS466',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS469',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS471',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS475',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS476',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS481',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS483',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS484',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS485',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS491',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS495',
    sensei: 'temp',
    grasshopper: 'temp' },
  { name: 'ICS499',
    sensei: 'temp',
    grasshopper: 'temp' },
];

/**
 * Initialize the Stuff collection if empty with seed data.
 */
if (Course.find().count() === 0) {
  _.each(courseSeeds, function seedCourses(course) {
    Course.insert(course);
  });
}
